version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Test suite
          command: npm test -- --ci --reporters=jest-junit --runInBand --coverage
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/results.xml

      - run:
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -f ./coverage/lcov.info

      - store_test_results:
          path: test-results
